ci: added master image publishing
aerogear/mobile-developer-console-operator pull request #65
Opened 2019-10-31 15:01 UTC by jhellar

## Motivation

https://issues.jboss.org/browse/AGMS-1135

## Changes

- change version of operand to `master`

2019-10-31 16:32 UTC, grdryn requested changes
The Jenkins pipeline already does the image build & push for the master tag. For now this is the one we prefer, since we trust the infrastructure that this runs on more.

2019-11-01 14:17 UTC, jhellar commented on Jenkinsfile
> +                DOCKER_DEV_TAG = getDevTag()
This will be available if [1] is merged.

[1] https://github.com/aerogear/qe-pipeline-library/pull/5

2019-11-01 14:24 UTC, jhellar commented
@grdryn ok, I've removed the circleci config. When looking at quay.io and jenkins, seems that latest changes on master were not published. I think that the reason for that is that there was no PR merged for them, the changes were just pushed to master from another branch. Do you know if that is the case? Can we maybe prevent from that by protecting pushing to master?

2019-11-01 17:05 UTC, grdryn commented
> @grdryn ok, I've removed the circleci config. When looking at quay.io and jenkins, seems that latest changes on master were not published. I think that the reason for that is that there was no PR merged for them, the changes were just pushed to master from another branch. Do you know if that is the case? Can we maybe prevent from that by protecting pushing to master?

Ugh, that's possible I guess. I've configured the "Merge Button" in a different way than before now, so maybe that will help. I'm also going to look into using prow for these repos, which would help this issue by handling all merges (the merge robot would perform merges rather than us unreliable humans). Until then, if we see that issue again, we can just hit the "build" button in jenkins for the master branch.

2019-11-04 08:53 UTC, jhellar commented on Jenkinsfile
> +                DOCKER_DEV_TAG = getDevTag()
already merged

2019-11-04 10:11 UTC, grdryn approved these changes
Approved.

Note that I'm still not convinced by this, but let's try it anyway. :+1:

2019-11-04 12:19 UTC, merged